### ISSUE TITLE
electron store

### ISSUE THREAD

**Issue by me-y** [CircleOnCircles/electron-svelte-template#2]
hello,

I am a not experienced at all. you recommend using electron-store with the maxatwork base you used.
I cant find where to put the require("electro-store") as svelte does not recognize require command.

Can you help ? I tried to use your boilerplate but I am facing another issue as yarn does not install properly on windows.

Thank you
regards

**Comment by ninyawee** [comment]
you could use ES6 import statement.
```
import * as store from "electron-store";
```
but I could use `require()` with no problem as well.
```js
// src/App.svelte
<script>
const Store = require("electron-store");
const store = new Store();

...

if (store.get("lottoes") === undefined) {
    lottoes = createEmptyLottoes();
</script>
```


I use this everyday on windows machine as well with some modification about command script. 
i'm not sure what was the error. It was likely to happen from incomplete installation, i guessed.

**Comment by me-y** [comment]
Reading your last phrase, I re installed the template and electron-store now works.
Lost my last evening;)
Big thank you
